# Generated by Django 3.0.1 on 2020-01-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_painter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopainter',
            name='begin_stroke',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='autopainter',
            name='follow_stroke',
            field=models.CharField(max_length=4096),
        ),
    ]
