# Generated by Django 3.0.1 on 2020-02-17 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auto_painter', '0002_auto_20200201_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopainter',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
