# Generated by Django 3.0.3 on 2020-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_painter', '0003_autopainter_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopainter',
            name='begin_stroke',
            field=models.TextField(max_length=21845),
        ),
        migrations.AlterField(
            model_name='autopainter',
            name='follow_stroke',
            field=models.TextField(max_length=21845),
        ),
    ]
